import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/navBar/page";
import { AlertProvider } from "@/contexts/AlertContext";
import ReduxProvider from "@/store/providers/ReduxProvider";
import { AuthProvider } from "@/store/providers/AuthProvider";

export const metadata: Metadata = {
  title: "CBMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ReduxProvider>
          <AlertProvider>
            <AuthProvider>{children}</AuthProvider>
          </AlertProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
